### ISSUE TITLE
bug-fix internall error

### ISSUE THREAD

**Issue by huddlestona** [mnguyenngo/reinforce-ml#24]
Error when submitting an answer.
see error from inspect:

Request URL: http://iyow.xyz/submit
Request Method: POST
Status Code: 500 INTERNAL SERVER ERROR
Remote Address: 54.203.42.134:80
Referrer Policy: no-referrer-when-downgrade

**Comment by mnguyenngo** [comment]
I created branch dev-024 to fix this.

**Comment by mnguyenngo** [comment]
Lines 12 and 13 were modified in app.py.

```python
# load pickle file with nlp data, check file name prior to deploying
scorer.load_nlp_pickle('../data/180606_def_nlp.pkl')
```

**Comment by mnguyenngo** [comment]
Site was fixed manually on the server since the pkl file name is different on the EC2.

See PR #25 
Merged into dev
